'use strict';
const $=id=>document.getElementById(id);
const brands={rose:'Rosé · Liso',thin:'Thin · Ultrafino',dreams:'Wild Dreams · Corrugado',longlove:'Long Love',fruit:'Fruit · Color y aroma',strong:'Strong · Extra Fuerte',xxl:'XXL · Extra Grande'};
const species={
 rose:{name:'Rosalía Terciopelo',brand:brands.rose,number:'01',image:'assets/rose.webp',description:'Seis brazos para abrazar el misterio. Cero ganas de pasar desapercibida.'},
 thin:{name:'Nimbo Susurro',brand:brands.thin,number:'02',image:'assets/thin.webp',description:'Aparece flotando, como un secreto que acaba de cobrar vida.'},
 dreams:{name:'Rulo Salvaje',brand:brands.dreams,number:'03',image:'assets/dreams.webp',description:'Mil pliegues, cuatro ojos y un talento especial para el caos.'},
 longlove:{name:'Don Sinprisa',brand:brands.longlove,number:'04',image:'assets/longlove.webp',description:'El reloj corre. Él no. Cada encuentro merece su propio tiempo.'},
 fruit:{name:'Tutti Frutti',brand:brands.fruit,number:'05',image:'assets/fruit.webp',description:'Una mezcla imposible de colores, colmillos y buen humor.'},
 strong:{name:'Bruno Blindado',brand:brands.strong,number:'06',image:'assets/strong.webp',description:'Una armadura dorada y un corazón que no sabe esconderse.'},
 xxl:{name:'Maximiliano XXL',brand:brands.xxl,number:'07',image:'assets/xxl.webp',description:'Enorme en tamaño. Gigante en curiosidad. Siempre queda lugar para una sorpresa.'}
};
let gameState={v:1,mask:0},collection={},canSave=true,storageError='';
try{gameState=AmorGame.read()}catch(e){canSave=false;storageError=e.message}
function syncCollection(){collection={};AmorGame.ids.forEach((id,i)=>{if(gameState.mask&(1<<i))collection[id]={capturedAt:null}})}
syncCollection();
let encounter=null,needsRemoval=false,absentSince=0,absentFrames=0,captureBusy=false;
let mode='welcome',stream=null,worker=null,ready=false,waiting=false,epoch=0,scanTimer=0,watchdog=0,active=null,lastQuad=null,lastSeen=0,stable=0,candidate=null,pose=null,toastTimer=0,captureTimer=0,starting=false,freshness=1100;
const video=$('camera'),sample=document.createElement('canvas'),ctx=sample.getContext('2d',{willReadFrequently:true});
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000)}
function imageClass(img,id){img.dataset.species=id;}
function renderCollection(){let ids=Object.keys(collection);$('collectionCount').textContent=ids.length+'/'+AmorGame.ids.length;$('saveInfo').textContent=canSave?'Tu colección y tu código se guardan en una cookie de este navegador.':storageError;$('cards').replaceChildren();for(let [id,s] of Object.entries(species)){let captured=collection[id],card=document.createElement('article');card.className='card'+(captured?'':' locked');let img=document.createElement('img');img.src=s.image;img.alt=captured?s.name:'Silueta de criatura no capturada';imageClass(img,id);let text=document.createElement('div');text.className='cardText';let tag=document.createElement('span');tag.className='tag';tag.textContent=captured?'CAPTURADO':'POR DESCUBRIR';let name=document.createElement('h3');name.textContent=captured?s.name:'Criatura '+s.number;let brand=document.createElement('p');brand.textContent=s.brand;let date=document.createElement('p');date.textContent=captured?'Guardado en tu colección':'Escaneá '+s.brand+' para encontrarlo.';text.append(tag,name,brand,date);card.append(img,text);$('cards').append(card)}$('rewardBtn').hidden=!gameState.reward&&ids.length!==AmorGame.ids.length;$('rewardBtn').disabled=!canSave;updateRewardImage()}
function openCollection(){renderCollection();$('collection').showModal()}
$('collectionBtn').onclick=openCollection;$('closeCollection').onclick=()=>$('collection').close();$('closeHelp').onclick=()=>$('helpDialog').close();$('help').onclick=()=>$('helpDialog').showModal();
for(const [id,label] of Object.entries(brands)){let figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src='targets/'+(id==='dreams'?'dreams-local':id)+'.jpg';img.alt='Envase Amor '+label;caption.textContent=label;figure.append(img,caption);$('targetExamples').append(figure)}
function show(id,isDemo=false){let s=species[id];if(!s)return;active=id;$('monster').src=s.image;$('monster').alt=s.name;imageClass($('monster'),id);$('creature').hidden=false;$('foundCard').hidden=false;$('reticle').hidden=true;$('brandLabel').textContent=isDemo?s.brand:(brands[candidate]||'Logo detectado');$('species').textContent='ESPECIE '+s.number;$('monsterName').textContent=s.name;$('monsterText').textContent=s.description;updateCapture(isDemo)}
function updateCapture(isDemo=mode==='demo'){let saved=active&&collection[active];$('capture').disabled=isDemo||!canSave||captureBusy||needsRemoval||!active||saved||stable<2||performance.now()-lastSeen>freshness;$('capture').replaceChildren(document.createTextNode(isDemo?'Vista demo · no se guarda':saved?'Ya está en tu colección':'Guardar encuentro'));}
function hideCreature(){active=null;pose=null;$('creature').hidden=true;$('foundCard').hidden=true;$('outline').querySelector('polygon').setAttribute('points','');$('reticle').hidden=mode!=='camera';$('capture').disabled=true}
function enter(next){encounter=null;needsRemoval=false;absentSince=0;absentFrames=0;mode=next;epoch++;$('welcome').hidden=true;$('scanner').hidden=false;$('footer').hidden=true;document.body.classList.add('scanning');document.body.classList.toggle('demo',next==='demo');$('modeLabel').textContent=next==='demo'?'MODO DEMO':'CÁMARA EN VIVO';$('demoControls').hidden=next!=='demo';$('sensorInfo').textContent=next==='demo'?'Vista previa de las criaturas':'Reconocimiento en el teléfono';hideCreature();candidate=null;stable=0;lastQuad=null;lastSeen=0;$('status').textContent=next==='camera'?'Mostrá el nombre de la variedad en el frente del envase Amor.':'Esta vista no cuenta como captura.'}
function releaseCamera(){if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;video.pause();video.srcObject=null}
function stop(){epoch++;mode='welcome';clearTimeout(scanTimer);clearTimeout(watchdog);clearTimeout(captureTimer);releaseCamera();waiting=false;document.body.classList.remove('scanning','demo','capturing');$('welcome').hidden=false;$('scanner').hidden=true;$('footer').hidden=false;hideCreature();$('start').disabled=!ready;starting=false}
function cameraError(e){if(e.name==='NotAllowedError'||e.name==='SecurityError')return 'Habilitá el permiso de cámara en tu navegador y volvé a intentar.';if(e.name==='NotFoundError')return 'No se encontró una cámara en este dispositivo.';if(e.name==='NotReadableError')return 'La cámara está ocupada. Cerrá la otra app que la esté usando.';return e.message||'No se pudo iniciar la cámara.'}
$('start').onclick=async()=>{if(starting||!ready)return;starting=true;$('start').disabled=true;$('setupStatus').textContent='Esperando permiso de cámara…';try{if(!isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('Abrí el enlace HTTPS publicado en un navegador para usar la cámara.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();enter('camera');$('setupStatus').textContent='Todo listo. El reconocimiento se realiza en tu teléfono.';scan()}catch(e){releaseCamera();$('setupStatus').textContent=cameraError(e);$('start').disabled=!ready}finally{starting=false}};
$('stop').onclick=stop;$('demo').onclick=()=>{if(starting)return;enter('demo');selectDemo()};
function selectDemo(){show($('demoSelect').value,true);pose={x:innerWidth*.5,y:innerHeight*.45,w:Math.min(innerWidth*.65,innerHeight*.43,330)};$('outline').querySelector('polygon').setAttribute('points','')}
$('demoSelect').onchange=selectDemo;
function scan(){if(mode!=='camera'||waiting||!ready)return;if($('collection').open||$('helpDialog').open||$('rewardDialog').open){scanTimer=setTimeout(scan,200);return}if(video.readyState<2){scanTimer=setTimeout(scan,150);return}let scale=Math.min(1,640/Math.max(innerWidth,innerHeight)),w=Math.round(innerWidth*scale),h=Math.round(innerHeight*scale);if(sample.width!==w||sample.height!==h){sample.width=w;sample.height=h}let vw=video.videoWidth,vh=video.videoHeight,s=Math.max(w/vw,h/vh),cw=w/s,ch=h/s;ctx.drawImage(video,(vw-cw)/2,(vh-ch)/2,cw,ch,0,0,w,h);let data=ctx.getImageData(0,0,w,h);waiting=true;clearTimeout(watchdog);watchdog=setTimeout(()=>{if(mode==='camera'){ready=false;stop();$('setupStatus').textContent='El reconocimiento no respondió. Recargá la página para volver a intentarlo.'}},12000);worker.postMessage({type:'frame',buffer:data.data.buffer,w,h,epoch},[data.data.buffer])}
function overlap(a,b){let box=q=>({x:Math.min(...q.map(p=>p.x)),y:Math.min(...q.map(p=>p.y)),r:Math.max(...q.map(p=>p.x)),b:Math.max(...q.map(p=>p.y))});let x=box(a),y=box(b),i=Math.max(0,Math.min(x.r,y.r)-Math.max(x.x,y.x))*Math.max(0,Math.min(x.b,y.b)-Math.max(x.y,y.y)),u=(x.r-x.x)*(x.b-x.y)+(y.r-y.x)*(y.b-y.y)-i;return i/(u||1)}
function receive(m){if(m.epoch!==epoch||mode!=='camera')return;waiting=false;clearTimeout(watchdog);freshness=Math.min(2500,Math.max(1100,m.ms*1.8));let result=m.result,now=performance.now();if(result&&Object.hasOwn(brands,result.id)){
 if(encounter&&encounter!==result.id){needsRemoval=false;encounter=null;}absentSince=0;absentFrames=0;let continuous=candidate===result.id&&lastQuad&&overlap(lastQuad,result.quad)>.2&&now-lastSeen<5000;stable=continuous?stable+1:1;candidate=result.id;lastQuad=result.quad;lastSeen=now;
 if(!needsRemoval){encounter=result.id;show(encounter);let points=result.quad.map(p=>({x:p.x*innerWidth/m.w,y:p.y*innerHeight/m.h}));let x=points.reduce((s,p)=>s+p.x,0)/4,y=points.reduce((s,p)=>s+p.y,0)/4,bw=Math.max(...points.map(p=>p.x))-Math.min(...points.map(p=>p.x)),bh=Math.max(...points.map(p=>p.y))-Math.min(...points.map(p=>p.y));pose={x,y,w:Math.min(innerWidth*.7,innerHeight*.42,Math.max(140,Math.max(bw,bh)*1.5))};$('outline').querySelector('polygon').setAttribute('points',points.map(p=>p.x+','+p.y).join(' '));$('status').textContent=collection[encounter]?'Esta criatura ya es parte de tu colección. Probá otra variedad.':'¡Un nuevo encuentro! Sumalo a tu colección.';
 }else{$('capture').disabled=true;$('status').textContent=needsRemoval?'¡Encuentro guardado! Buscá otra variedad.':'Confirmando la variedad… Mantené el teléfono quieto.'}
 }else{stable=0;if(now-lastSeen>1800){stable=0;candidate=null;lastQuad=null;}$('capture').disabled=true;if(!absentSince)absentSince=now;absentFrames++;if(absentFrames>=3&&now-absentSince>=1200){encounter=null;needsRemoval=false;hideCreature();$('status').textContent='Buscá otra variedad de Amor para completar el encuentro.'}else if(now-lastSeen>freshness){hideCreature();$('status').textContent='Buscando una variedad Amor…'}}
 scanTimer=setTimeout(scan,Math.max(50,220-m.ms))}
$('capture').onclick=async()=>{if(mode!=='camera'||!active||!canSave||captureBusy||needsRemoval||stable<2||performance.now()-lastSeen>freshness||collection[active])return;let id=active;captureBusy=true;updateCapture();try{gameState=await AmorGame.capture(id);syncCollection();needsRemoval=active===id;renderCollection();document.body.classList.add('capturing');navigator.vibrate?.([50,30,100]);notify(species[id].name+' capturado. '+AmorGame.count(gameState)+'/'+AmorGame.ids.length);clearTimeout(captureTimer);captureTimer=setTimeout(()=>document.body.classList.remove('capturing'),700);if(gameState.mask===127)openReward()}catch(e){notify(e.message)}finally{captureBusy=false;updateCapture()}};
function updateRewardImage(){if(gameState.reward){$('rewardImage').src=gameState.reward.image;$('downloadQR').href=gameState.reward.image;$('rewardNote').textContent='Este es tu código guardado. Se mostrará siempre el mismo.'}else $('rewardNote').textContent='Reuní las siete criaturas para obtener tu código.'}
function openReward(){updateRewardImage();if(!$('rewardDialog').open)$('rewardDialog').showModal()}
$('rewardBtn').onclick=async()=>{try{gameState=await AmorGame.restoreReward();syncCollection();renderCollection();if(gameState.reward)openReward()}catch(e){notify(e.message)}};
$('closeReward').onclick=()=>$('rewardDialog').close();
let smoothed=null;
function animate(){requestAnimationFrame(animate);if(pose&&active){if(!smoothed)smoothed={...pose};for(let k of ['x','y','w'])smoothed[k]+=(pose[k]-smoothed[k])*.22;let el=$('creature');el.style.left=smoothed.x+'px';el.style.top=smoothed.y+'px';el.style.width=smoothed.w+'px';el.style.height=smoothed.w*1.1+'px';el.style.opacity=mode==='demo'||performance.now()-lastSeen<freshness?'1':'.35';if(mode==='camera'&&performance.now()-lastSeen>freshness)$('capture').disabled=true}else smoothed=null}
function init(){for(const src of new Set(Object.values(species).map(s=>s.image))){let image=new Image();image.src=src;}renderCollection();if(storageError){$('setupStatus').textContent=storageError;$('start').disabled=true;animate();return}$('start').disabled=true;if(!('Worker' in window)||!ctx){$('setupStatus').textContent='Este navegador no permite el reconocimiento local. Podés ver las criaturas en modo demo.';return}try{worker=new Worker('detector-worker.js?v=amor-2');worker.onmessage=e=>{let m=e.data;if(m.type==='ready'){ready=true;$('start').disabled=false;$('setupStatus').textContent='Tu próximo encuentro está listo. Enfocá el nombre de la variedad.'}else if(m.type==='result')receive(m);else if(m.type==='error'){ready=false;if(mode==='camera')stop();$('start').disabled=true;$('setupStatus').textContent=m.message}};worker.onerror=()=>{ready=false;if(mode==='camera')stop();$('start').disabled=true;$('setupStatus').textContent='No se pudo cargar el detector. Recargá la página. El modo demo sigue disponible.'}}catch(e){$('setupStatus').textContent='No se pudo iniciar el detector. Abrí el sitio publicado con HTTPS.'}animate()}
window.addEventListener('resize',()=>{if(mode==='demo')selectDemo();if(mode==='camera'){lastQuad=null;stable=0;hideCreature()}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='camera')stop()});window.addEventListener('pagehide',()=>{releaseCamera();worker?.terminate()});window.addEventListener('pageshow',e=>{if(e.persisted)location.reload()});
init();
if(gameState.mask===127&&!gameState.reward)AmorGame.restoreReward().then(s=>{gameState=s;syncCollection();renderCollection()}).catch(e=>notify(e.message));
window.addEventListener('focus',()=>{try{gameState=AmorGame.read();syncCollection();renderCollection();updateCapture()}catch(e){canSave=false;storageError=e.message;notify(e.message)}});

document.querySelectorAll('[data-preview]').forEach(button=>button.onclick=()=>{if(starting)return;if(mode==='camera')stop();$('demoSelect').value=button.dataset.preview;enter('demo');selectDemo();});
