const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const http=require('node:http');const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const server=http.createServer((req,res)=>{let file=path.join(root,req.url.split('?')[0]);if(file.endsWith('/'))file+='index.html';try{res.setHeader('Content-Type',({'.js':'text/javascript','.html':'text/html','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),p=await context.newPage();const url=`http://127.0.0.1:${server.address().port}/verificadoramor/`;await p.goto(url);await p.locator('summary').click();
 const value='PREMIO:AMOR:12345678-1234-4234-8234-123456789abc';
 async function submit(value){await p.locator('#payload').fill(value);await p.locator('#manual button').click();await p.waitForFunction(()=>!document.querySelector('#result').hidden);}
 await submit(value);assert.equal(await p.locator('#resultTitle').textContent(),'OK');assert.equal(await p.locator('#resultIcon').textContent(),'✓');
 await p.reload();await p.locator('summary').click();await submit(value);assert.equal(await p.locator('#resultTitle').textContent(),'Este ya había sido leído');assert.notEqual(await p.locator('#resultIcon').textContent(),'✓');
 await submit(value.toUpperCase());assert.equal(await p.locator('#resultTitle').textContent(),'Este ya había sido leído');
 for(const invalid of ['PREMIO:KINGJR:12345678-1234-4234-8234-123456789abc','https://example.com','PREMIO:AMOR:------------------------------------','PREMIO:OTHER:12345678-1234-4234-8234-123456789abc']){await submit(invalid);assert.equal(await p.locator('#resultTitle').textContent(),'QR no válido');assert.notEqual(await p.locator('#resultIcon').textContent(),'✓');}
 const second=await context.newPage();await second.goto(url);const simultaneous='PREMIO:AMOR:22345678-1234-4234-8234-123456789abc';
 const statuses=await Promise.all([p,second].map(page=>page.evaluate(async value=>(await AmorVerifier.verify(value)).status,simultaneous)));assert.deepEqual(statuses.sort(),['duplicate','ok']);
 // Decode a QR generated by the game's own encoder, then pass it through the UI.
 await p.addScriptTag({url:`http://127.0.0.1:${server.address().port}/amor/vendor/qrcode.js`});
 const decoded=await p.evaluate(async()=>{const qr=qrcode(0,'M');const payload='PREMIO:AMOR:32345678-1234-4234-8234-123456789abc';qr.addData(payload,'Byte');qr.make();const image=new Image();image.src=qr.createDataURL(5,20);await image.decode();const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,c.width,c.height);return jsQR(data.data,data.width,data.height).data;});
 await submit(decoded);assert.equal(await p.locator('#resultTitle').textContent(),'OK');
 await p.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('quota')};});await submit('PREMIO:AMOR:42345678-1234-4234-8234-123456789abc');assert.equal(await p.locator('#resultTitle').textContent(),'No se pudo registrar');assert.notEqual(await p.locator('#resultIcon').textContent(),'✓');
 await p.reload();await p.evaluate(()=>localStorage.setItem(AmorVerifier.key,'broken'));await p.locator('summary').click();await submit(value);assert.equal(await p.locator('#resultTitle').textContent(),'No se pudo registrar');
 await p.evaluate(()=>localStorage.removeItem(AmorVerifier.key));await p.reload();await p.screenshot({path:'/tmp/amor-verifier.png',fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 console.log('PASS: first scan, persisted duplicate, no tick on duplicates/invalid/error, case normalization, concurrent tabs, actual game QR decoding, blocked/corrupt storage, mobile layout.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
